# Generated by Django 5.0.7 on 2024-08-26 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=35)),
                ('MiddleName', models.CharField(max_length=35)),
                ('LastName', models.CharField(max_length=35)),
                ('FatherName', models.CharField(max_length=50)),
                ('MotherName', models.CharField(max_length=50)),
                ('Adhaar_Number', models.CharField(max_length=12, unique=True)),
                ('Address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_number', models.CharField(editable=False, max_length=15, unique=True)),
                ('Pin_Number', models.CharField(max_length=256)),
                ('Balance_Amount', models.BigIntegerField(default=0)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acc_type')),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
            ],
        ),
    ]
