# Generated by Django 5.0.7 on 2024-08-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
