# Generated by Django 5.0.7 on 2024-08-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bank_otp_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='otp_attempts',
        ),
    ]
