# Generated by Django 5.0.7 on 2024-08-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_address_bank_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='acc_type',
            new_name='Acc_Type',
        ),
    ]
