# Generated by Django 5.0.7 on 2024-08-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_acc_type_bank_acc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='adhaar_number',
            new_name='Adhaar_Number',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='balance_amount',
            new_name='Balance_Amount',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='father_name',
            new_name='FatherName',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='first_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='middle_name',
            new_name='MiddleName',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='mother_name',
            new_name='MotherName',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='pin_number',
            new_name='Pin_Number',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='Acc_Type',
            new_name='acc_type',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='otp_blocked_until',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
